/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registro de usuario local (email + contraseña)
         * @description Crea un usuario local (US-01). La unicidad del email se garantiza a nivel de base de datos:
         *     dos registros simultáneos dan un 201 y el otro 409. Si el email ya pertenece a una cuenta
         *     solo-Google se responde 409 `ACCOUNT_EXISTS_WITH_GOOGLE` (el cliente sugiere entrar con
         *     Google); si pertenece a una cuenta local, 409 `EMAIL_ALREADY_EXISTS` (sin auto-linking, US-08).
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inicio de sesión local (email + contraseña)
         * @description Autentica credenciales locales y devuelve el par de tokens (US-02). Anti-enumeración: email
         *     inexistente y contraseña incorrecta producen exactamente el mismo 401 `INVALID_CREDENTIALS`, y
         *     el tiempo de respuesta no delata si el email existe (verificación contra hash ficticio). La
         *     colisión con Google (US-08 AC-04) no se revela aquí: siempre 401 genérico.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refrescar el par de tokens con rotación
         * @description Intercambia un refresh válido y vigente por un par NUEVO (US-03). Cada refresco invalida el
         *     token usado (rotación). Si se presenta un refresh ya usado (reuso), la respuesta es el mismo
         *     401 genérico Y se revoca TODA la familia de refresh del usuario (el atacante no debe saber
         *     que el reuso fue detectado).
         */
        post: operations["refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cerrar sesión (revocar refresh)
         * @description Revoca el refresh en base (US-04). El access vigente no se revoca explícitamente: expira solo
         *     por su corta vida (5-15 min, comportamiento esperado). Si el refresh revocado se presenta
         *     después en /refresh, el reuso revoca toda la familia.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión con Google (OIDC — GIS token flow)
         * @description Intercambia un ID token de Google por el par de tokens del proyecto (US-07). La verificación es
         *     estrictamente server-side con jose contra el JWKS de accounts.google.com (caché): `aud` =
         *     client_id configurado, `iss` = accounts.google.com, `iat`/`exp` en ventana, algoritmo RS256
         *     fijado. **Anti-replay (nonce)**: si el ID token incluye el claim `nonce`, el campo `nonce` del
         *     body ES obligatorio y DEBE coincidir — si no, 401 `UNAUTHORIZED`; si el ID token no incluye
         *     `nonce`, el campo `nonce` del body se ignora. El claim `email_verified` debe ser `true`, si no →
         *     401 `EMAIL_NOT_VERIFIED`. Primer inicio = alta implícita (email de Google, sin contraseña,
         *     `email_verified = 1`). Si el email ya existe como usuario solo-local → 409 `EMAIL_ALREADY_EXISTS`
         *     sin auto-linking (US-08 AC-02). La sesión usa NUESTROS refresh tokens (misma rotación/reuso).
         */
        post: operations["loginGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recurso protegido — datos del usuario autenticado
         * @description Devuelve los datos del usuario autenticado por el access token (US-05). El recurso responde
         *     SOLO con datos del propio token (nunca de otro usuario). Forma de 401 idéntica para token
         *     ausente, malformado, vencido o con firma inválida (el algoritmo de verificación está fijado,
         *     nunca se toma del header `alg`).
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic-link/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solicitar magic link (sign in sin contraseña)
         * @description Genera y envía un enlace de acceso por email (US-09). La respuesta `200 { data: { ok: true } }`
         *     es **idéntica** exista o no el email, y se realiza la misma cantidad de trabajo (generar token,
         *     persistir su hash, enviar email) en ambos casos — anti-enumeración estricta: ni la respuesta ni
         *     un side-channel temporal revelan si la cuenta está registrada. El servidor persiste solo el
         *     **hash SHA-256** del token opaco (≥ 32 bytes aleatorios), nunca el token en claro. El enlace
         *     expira en un TTL corto configurable (`MAGIC_LINK_TTL_MINUTES`, default 15, máx 60). La auto-cuenta
         *     se resuelve en el consume (US-10 AC-02): un link enviado a un email no registrado crea la cuenta.
         *     El campo `intent` selecciona el canal (US-11/12): `login` (default) envía la URL de consumo de
         *     sesión; `password_reset` envía la URL de recuperación de contraseña con la MISMA forma de respuesta
         *     y la MISMA cantidad de trabajo (anti-enumeración también en el canal de recuperación).
         */
        post: operations["requestMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/magic-link/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consumir magic link (login por enlace)
         * @description Intercambia un token de magic link válido y vigente por el par de tokens (US-10). La respuesta
         *     tiene la misma forma que `/login` (el cliente no distingue el proveedor). **Auto-cuenta**: si el
         *     email del link no está registrado, se crea el usuario (`provider = 'magic'`, `email_verified = 1`)
         *     y se responde 200. Si ya está registrado (local/Google), se marca `email_verified = 1` y se emite
         *     sesión sobre la cuenta existente. **Un solo uso**: el token se marca `used` al consumirse. Token
         *     inexistente, revocado o vencido → 401 `MAGIC_LINK_INVALID`, idéntico en forma (anti-enumeración).
         *     El consumo de sesión solo acepta enlaces `purpose = 'login'`: un enlace de recuperación
         *     (`password_reset`) presentado aquí responde el mismo 401 idéntico (US-12 F3).
         */
        post: operations["consumeMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cambiar contraseña (usuario autenticado)
         * @description Reemplaza la contraseña del usuario autenticado probando la actual (US-11). Requiere access
         *     token (Bearer). La contraseña actual incorrecta → 401 `INVALID_CREDENTIALS` genérico (misma
         *     semántica que /login, anti-enumeración). Cuenta sin contraseña configurada (solo-Google o
         *     solo-magic) → 409 `ACCOUNT_HAS_NO_PASSWORD`. **F1**: el cambio revoca TODAS las sesiones del
         *     usuario (`revokeFamily`) — compensa sesiones emitidas bajo el secreto viejo; el cliente
         *     re-autentica. El access vigente no se revoca explícitamente: expira solo por su corta vida
         *     (5-15 min), comportamiento esperado.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recuperar contraseña (consumo del magic link de reset)
         * @description Consume un magic link emitido con `intent: password_reset` y reemplaza (o asigna) la
         *     contraseña del email del enlace (US-12). El token ES la credencial: la ruta solo lleva
         *     `authLimiter` (sin requireAuth). **NO emite sesión** — respuesta `204`; el cliente redirige
         *     al login con el secreto nuevo. **F2**: email aún no registrado → auto-cuenta local (el enlace
         *     prueba la posesión del email, coherente con US-10 AC-02). **F1**: el reset revoca TODAS las
         *     sesiones del usuario. Token inexistente, vencido, ya usado o de otro propósito (`login`) →
         *     401 `MAGIC_LINK_INVALID`, idéntico en forma (anti-enumeración).
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: email
         * @description Email normalizado a minúsculas (Value Object del dominio, sección 6.1).
         * @example ana@example.com
         */
        Email: string;
        /**
         * @description NIST 800-63B — por longitud, sin reglas de complejidad. Solo hash argon2id en reposo.
         * @example contraseñaSegura123
         */
        Password: string;
        CredentialsRequest: {
            email: components["schemas"]["Email"];
            password: components["schemas"]["Password"];
        };
        ChangePasswordRequest: {
            currentPassword: components["schemas"]["Password"];
            newPassword: components["schemas"]["Password"];
        };
        PasswordResetRequest: {
            token: components["schemas"]["MagicLinkToken"];
            password: components["schemas"]["Password"];
        };
        RefreshRequest: {
            refreshToken: components["schemas"]["RefreshToken"];
        };
        GoogleRequest: {
            /**
             * @description ID token JWT RS256 firmado por Google (accounts.google.com). Viaja en el body, nunca como Authorization (US-07).
             * @example eyJhbGciOiJSUzI1NiIsImtpZCI6InNpZ25pbmcta2V5LTEifQ.ejemplo-claims.ejemplo-firma
             */
            idToken: string;
            /**
             * @description Nonce de alta entropía generado por el cliente (app/web) y usado al solicitar el ID token a Google.
             *     Anti-replay: si el ID token incluye el claim `nonce`, este campo es obligatorio y DEBE coincidir
             *     (si no → 401 UNAUTHORIZED); si el ID token no lo incluye, se ignora. Opcional en el schema por el
             *     flujo condicional de Google (no siempre emite nonce), no porque sea prescindible cuando sí existe.
             * @example vZ3mX9qK2rT8wY5bN1cL7pD0sF4hJ6a
             */
            nonce?: string;
        };
        /**
         * @description Canal del magic link (US-09/10 vs US-12). `login` (default) → enlace de acceso con sesión;
         *     `password_reset` → enlace de recuperación de contraseña (misma forma de respuesta y mismo
         *     trabajo realizado — anti-enumeración también en el reset). Se persiste en `magic_links.purpose`.
         * @example login
         * @enum {string}
         */
        MagicLinkIntent: "login" | "password_reset";
        MagicLinkRequest: {
            email: components["schemas"]["Email"];
            intent?: components["schemas"]["MagicLinkIntent"];
        };
        MagicLinkRequestResponse: {
            data: {
                /**
                 * @description Siempre true — respuesta idéntica exista o no el email (anti-enumeración, US-09 AC-02).
                 * @example true
                 */
                ok: boolean;
            };
        };
        /**
         * @description Token opaco aleatorio (≥ 32 bytes, base64url) que viaja en la URL de consumo `?token=<opaco>`.
         *     El servidor persiste solo su hash SHA-256. Un solo uso; TTL corto configurable (US-09 AC-03/AC-04).
         * @example ejOpc0aQnFgW4s9XyZ2bCdEfGhIjKlMnOpQrStUvWx
         */
        MagicLinkToken: string;
        MagicLinkConsumeRequest: {
            token: components["schemas"]["MagicLinkToken"];
        };
        /**
         * @description JWT HS256 del proyecto. Claims: sub (users.id), iss, aud, exp, iat, nbf y jti.
         *     Vigencia 5-15 min. Algoritmo fijado en el servidor (jamás del header alg).
         * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ejemplo.ejemplo_firma
         */
        AccessToken: string;
        /**
         * @description Token opaco (no-JWT) con vigencia de 7-30 días. El servidor guarda solo su hash SHA-256 + jti;
         *     se rota en cada refresh y el reuso revoca toda la familia.
         * @example v4.local.ejemplo-opaco-solo-server
         */
        RefreshToken: string;
        UserPublic: {
            /**
             * Format: uuid
             * @description UUID v4 de users.id (nunca una clave autoincremental).
             * @example 9f0c7a2e-4b6d-4c8a-9f2e-3a1b2c3d4e5f
             */
            id: string;
            email: components["schemas"]["Email"];
            /**
             * Format: date-time
             * @description Fecha de alta del usuario.
             * @example 2026-08-27T10:15:30.000Z
             */
            createdAt: string;
        };
        AuthResponse: {
            data: {
                accessToken: components["schemas"]["AccessToken"];
                refreshToken: components["schemas"]["RefreshToken"];
                user: components["schemas"]["UserPublic"];
            };
        };
        RefreshResponse: {
            data: {
                accessToken: components["schemas"]["AccessToken"];
                refreshToken: components["schemas"]["RefreshToken"];
            };
        };
        UserResponse: {
            data: components["schemas"]["UserPublic"];
        };
        ValidationIssue: {
            /**
             * @description Campo del payload que falló la validación.
             * @example email
             */
            field: string;
            /**
             * @description Identificador estable del problema (zod).
             * @example invalid_email
             */
            issue: string;
        };
        Error: {
            error: {
                /**
                 * @description Identificador estable y programable. Complemento del catálogo de US-06: los códigos
                 *     documentados son VALIDATION_ERROR, INVALID_CREDENTIALS, EMAIL_ALREADY_EXISTS,
                 *     ACCOUNT_EXISTS_WITH_GOOGLE, EMAIL_NOT_VERIFIED, MAGIC_LINK_INVALID,
                 *     ACCOUNT_HAS_NO_PASSWORD y RATE_LIMITED; UNAUTHORIZED y MALFORMED_REQUEST completan la
                 *     matriz 401/400; NOT_FOUND y METHOD_NOT_ALLOWED cubren el 404/405 centralizado
                 *     (doc 00 → ítem 24); INTERNAL_ERROR para 500.
                 * @enum {string}
                 */
                code: "VALIDATION_ERROR" | "INVALID_CREDENTIALS" | "EMAIL_ALREADY_EXISTS" | "ACCOUNT_EXISTS_WITH_GOOGLE" | "EMAIL_NOT_VERIFIED" | "MAGIC_LINK_INVALID" | "ACCOUNT_HAS_NO_PASSWORD" | "RATE_LIMITED" | "UNAUTHORIZED" | "MALFORMED_REQUEST" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "INTERNAL_ERROR";
                /** @description Mensaje legible por humanos; genérico e idéntico en 401 (anti-enumeración). */
                message: string;
                /** @description Opcional; estructura los errores de validación por campo y el proveedor sugerido en 409. */
                details?: components["schemas"]["ValidationIssue"][];
                /**
                 * @description Correlación con los logs estructurados (pino-http, doc 00 → ítem 11).
                 * @example req_01J4X8K2YQ
                 */
                requestId: string;
            };
        };
    };
    responses: {
        /** @description JSON/body malformado o header inválido — envelope sin detalles internos. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description No autenticado: token ausente, malformado, vencido o con firma no verificada. Respuesta
         *     idéntica en forma para todos los casos (nunca revela la causa exacta). En /refresh, el reuso
         *     detectado responde igual pero además revoca toda la familia (US-03 AC-03).
         */
        UnauthorizedGeneric: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Credenciales incorrectas — idéntico para email inexistente y contraseña equivocada
         *     (anti-enumeración, doc 00 → ítem 41).
         */
        UnauthorizedInvalidCredentials: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Falla de validación de negocio (zod) — details por campo, preceden a cualquier verificación. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit excedido (registro/login/refresh/google; por IP, y también por email en login). */
        RateLimited: {
            headers: {
                /**
                 * @description Segundos antes de poder reintentar.
                 * @example 60
                 */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Error inesperado o de infraestructura — jamás stack traces, rutas internas ni valores sensibles (doc 00 → ítem 20). */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRequest"];
            };
        };
        responses: {
            /** @description Usuario creado; se devuelve el par de tokens y el perfil público. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Conflicto de identidad — el email ya está registrado. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRequest"];
            };
        };
        responses: {
            /** @description Credenciales correctas; par de tokens y perfil público. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["UnauthorizedInvalidCredentials"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    refreshTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Par de tokens nuevo; el refresh anterior queda invalidado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["UnauthorizedGeneric"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Refresh revocado correctamente (US-04 AC-01). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["UnauthorizedGeneric"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    loginGoogle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleRequest"];
            };
        };
        responses: {
            /** @description Sesión iniciada; mismo contrato que /login (el cliente no distingue el proveedor). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description ID token de Google inválido o email no verificado — verificación server-side. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflicto de identidad — el email ya pertenece a una cuenta solo-local. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Datos del usuario autenticado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["UnauthorizedGeneric"];
            500: components["responses"]["InternalError"];
        };
    };
    requestMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkRequest"];
            };
        };
        responses: {
            /** @description Enlace enviado (o no) — respuesta idéntica siempre (anti-enumeración). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagicLinkRequestResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    consumeMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkConsumeRequest"];
            };
        };
        responses: {
            /** @description Sesión iniciada; mismo contrato que /login / /auth/google. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Token inexistente, revocado o vencido — forma idéntica (anti-enumeración). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Contraseña actualizada y todas las sesiones revocadas (US-11 AC-01/AC-02). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            /**
             * @description No autenticado (token ausente/vencido/malformado/firma no verificada, `UNAUTHORIZED`) o
             *     contraseña actual incorrecta (`INVALID_CREDENTIALS`).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La cuenta no tiene contraseña configurada (solo-Google o solo-magic). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Contraseña reemplazada/asignada y sesiones revocadas; sin sesión emitida (US-12 AC-01/AC-02). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            /** @description Token inexistente, vencido, ya usado o de otro propósito — forma idéntica (anti-enumeración). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
}
